name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: "**/build/libs/*.jar"
          retention-days: 7
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Upload plugin jar
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.TESTNET_USERNAME }}
          server: ${{ secrets.TESTNET_HOST }}
          port: ${{ secrets.TESTNET_PORT }}
          local_path: './bot-paper.jar'
          remote_path: ${{ secrets.TESTNET_DEST }}
          sftp_only: true
          password: ${{ secrets.TESTNET_PASSWORD }}
      - name: Restart Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TESTNET_HOST }}
          username: ${{ secrets.TESTNET_USERNAME }}
          password: ${{ secrets.TESTNET_PASSWORD }}
          port: ${{ secrets.TESTNET_PORT }}
          script: ./restart_prac ${{ github.ref }}